#!/usr/bin/env python3
import os
import matplotlib.pyplot as plt
from byzfl.utils.misc import load_accuracy

def main():
    results_dir = "./results/cnn_cifar_tuning"
    if not os.path.exists(results_dir):
        print(f"Error: {results_dir} not found.")
        return

    models = ["cnn_cifar", "cnn_cifar_tanh"]
    lrs = [0.1, 0.05, 0.01]
    
    plt.figure(figsize=(10, 6))
    
    for model in models:
        for lr in lrs:
            # Reconstruct the expected folder name format generated by ByzFL
            # e.g., cifar10_cnn_cifar_n_10_f_0_d_0_gamma_similarity_niid_1.0_Average_NNM_ARC_SignFlipping_lr_0.05_mom_0.9_wd_0.0001
            folder_name = f"cifar10_{model}_n_10_f_0_d_0_gamma_similarity_niid_1.0_Average_NNM_ARC_SignFlipping_lr_{lr}_mom_0.9_wd_0.0001"
            folder_path = os.path.join(results_dir, folder_name)
            
            if os.path.exists(folder_path):
                try:
                    # Load accuracy (list of length nb_steps/evaluation_delta)
                    acc = load_accuracy(folder_path)
                    # ByzFL load_accuracy returns a dict with 'test_accuracy' usually if new version, or just the list if old version
                    # Let's handle both
                    if isinstance(acc, dict) and 'test_accuracy' in acc:
                        y = acc['test_accuracy']
                    else:
                        y = acc
                    
                    x = [i * 100 for i in range(len(y))]  # evaluation_delta is 100
                    plt.plot(x, y, label=f"{model} (LR={lr})")
                except Exception as e:
                    print(f"Could not load data for {folder_name}: {e}")
            else:
                print(f"Folder not found: {folder_path}")

    plt.title("CIFAR-10 Baseline Tuning (ReLU vs Tanh)")
    plt.xlabel("Training Steps")
    plt.ylabel("Test Accuracy")
    plt.legend()
    os.makedirs("results/plots/cifar_tuning", exist_ok=True)
    plot_path = "results/plots/cifar_tuning/tuning_results.png"
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    print(f"Saved plot to {plot_path}")

if __name__ == "__main__":
    main()
